name: digitalocean-sample-aspnet
services:
- dockerfile_path: ./aspnetapp/Dockerfile
  github:
    branch: tmp
    deploy_on_push: true
    repo: caldrianx/digitalocean-sample-aspnet
  name: digitalocean-sample-aspnet
